const defaultTheme = require("tailwindcss/defaultTheme");
// const colors = require("./lightColors.json");

const colors = {
  neutral: {
    "bg-base": "var(--neutral-bg-base, #ffffffff)",
    "bg-base-disabled": "var(--neutral-bg-base-disabled, #fafafaff)",
    bg: "var(--neutral-bg, #fafafaff)",
    "bg-weak": "var(--neutral-bg-weak, #edededff)",
    "bg-strong": "var(--neutral-bg-strong, #b3b3b3ff)",
    "bg-strong-disabled": "var(--neutral-bg-strong-disabled, #e2e2e2ff)",
    border: "var(--neutral-border, #737373ff)",
    "border-active": "var(--neutral-border-active, #474747ff)",
    "border-weak": "var(--neutral-border-weak, #ccccccff)",
    "border-weak-hover": "var(--neutral-border-weak-hover, #8c8c8cff)",
    "border-disabled": "var(--neutral-border-disabled, #e2e2e2ff)",
    text: "var(--neutral-text, #212121ff)",
    "text-weak": "var(--neutral-text-weak, #474747ff)",
    "text-subtle": "var(--neutral-text-subtle, #737373ff)",
    "text-strong": "var(--neutral-text-strong, #ffffffff)",
    "text-disabled": "var(--neutral-text-disabled, #b3b3b3ff)",
    icon: "var(--neutral-icon, #737373ff)",
    "icon-hover": "var(--neutral-icon-hover, #5e5e5eff)",
    "icon-active": "var(--neutral-icon-active, #474747ff)",
    "icon-weak": "var(--neutral-icon-weak, #8c8c8cff)",
    "icon-medium": "var(--neutral-icon-medium, #474747ff)",
    "icon-strong": "var(--neutral-icon-strong, #ffffffff)",
    "icon-disabled": "var(--neutral-icon-disabled, #b3b3b3ff)",
  },
  action: {
    bg: "var(--action-bg, #047ab5ff)",
    "bg-hover": "var(--action-bg-hover, #096499ff)",
    "bg-active": "var(--action-bg-active, #0c4b78ff)",
    "bg-base-hover": "var(--action-bg-base-hover, #f0fdffff)",
    "bg-base-active": "var(--action-bg-base-active, #f0fdffff)",
    "bg-subtle": "var(--action-bg-subtle, #f0fdffff)",
    "bg-weak": "var(--action-bg-weak, #d9faffff)",
    "bg-disabled": "var(--action-bg-disabled, #b7eaf4ff)",
    border: "var(--action-border, #047ab5ff)",
    "border-active": "var(--action-border-active, #0c4b78ff)",
    "border-weak-hover": "var(--action-border-weak-hover, #047ab5ff)",
    "border-weak-focus": "var(--action-border-weak-focus, #047ab5ff)",
    text: "var(--action-text, #047ab5ff)",
    "text-hover": "var(--action-text-hover, #096499ff)",
    "text-active": "var(--action-text-active, #0c4b78ff)",
    icon: "var(--action-icon, #047ab5ff)",
    "icon-hover": "var(--action-icon-hover, #096499ff)",
    "icon-active": "var(--action-icon-active, #0c4b78ff)",
    "icon-weak": "var(--action-icon-weak, #0294c9ff)",
    "icon-disabled": "var(--action-icon-disabled, #b7eaf4ff)",
  },
  danger: {
    bg: "var(--danger-bg, #d43737ff)",
    "bg-hover": "var(--danger-bg-hover, #b81e26ff)",
    "bg-active": "var(--danger-bg-active, #8f1416ff)",
    "bg-base-hover": "var(--danger-bg-base-hover, #f0fdffff)",
    "bg-base-active": "var(--danger-bg-base-active, #fff7f8ff)",
    "bg-subtle": "var(--danger-bg-subtle, #fff7f8ff)",
    "bg-weak": "var(--danger-bg-weak, #ffe8ecff)",
    border: "var(--danger-border, #d43737ff)",
    "border-active": "var(--danger-border-active, #8f1416ff)",
    "border-weak-hover": "var(--danger-border-weak-hover, #d43737ff)",
    text: "var(--danger-text, #d43737ff)",
    "text-hover": "var(--danger-text-hover, #d43737ff)",
    "text-active": "var(--danger-text-active, #8f1416ff)",
    icon: "var(--danger-icon, #d43737ff)",
    "icon-hover": "var(--danger-icon-hover, #b81e26ff)",
    "icon-active": "var(--danger-icon-active, #8f1416ff)",
    "icon-weak": "var(--danger-icon-weak, #e95d62ff)",
  },
  success: {
    bg: "var(--success-bg, #208504ff)",
    "bg-hover": "var(--success-bg-hover, #196e03ff)",
    "bg-active": "var(--success-bg-active, #105401ff)",
    "bg-base-hover": "var(--success-bg-base-hover, #f0fdffff)",
    "bg-base-active": "var(--success-bg-base-active, #f4fef1ff)",
    "bg-subtle": "var(--success-bg-subtle, #f4fef1ff)",
    "bg-weak": "var(--success-bg-weak, #dbfcd1ff)",
    border: "var(--success-border, #208504ff)",
    "border-active": "var(--success-border-active, #105401ff)",
    "border-weak-hover": "var(--success-border-weak-hover, #208504ff)",
    text: "var(--success-text, #208504ff)",
    "text-hover": "var(--success-text-hover, #196e03ff)",
    "text-active": "var(--success-text-active, #105401ff)",
    icon: "var(--success-icon, #208504ff)",
    "icon-hover": "var(--success-icon-hover, #196e03ff)",
    "icon-active": "var(--success-icon-active, #105401ff)",
    "icon-weak": "var(--success-icon-weak, #32a113ff)",
  },
  warning: {
    bg: "var(--warning-bg, #bd5302ff)",
    "bg-hover": "var(--warning-bg-hover, #9b4703ff)",
    "bg-active": "var(--warning-bg-active, #783302ff)",
    "bg-base-hover": "var(--warning-bg-base-hover, #fff8f2ff)",
    "bg-base-active": "var(--warning-bg-base-active, #fff8f2ff)",
    "bg-subtle": "var(--warning-bg-subtle, #fff8f2ff)",
    "bg-weak": "var(--warning-bg-weak, #ffefe0ff)",
    border: "var(--warning-border, #bd5302ff)",
    "border-active": "var(--warning-border-active, #783302ff)",
    "border-weak-hover": "var(--warning-border-weak-hover, #bd5302ff)",
    text: "var(--warning-text, #bd5302ff)",
    "text-hover": "var(--warning-text-hover, #9b4703ff)",
    "text-active": "var(--warning-text-active, #783302ff)",
    icon: "var(--warning-icon, #bd5302ff)",
    "icon-hover": "var(--warning-icon-hover, #9b4703ff)",
    "icon-active": "var(--warning-icon-active, #783302ff)",
    "icon-weak": "var(--warning-icon-weak, #e07000ff)",
  },
  overlay: {
    "bg-strong": "var(--overlay-bg-strong, #474747f5)",
    "bg-medium": "var(--overlay-bg-medium, #103b5c80)",
    "bg-weak": "var(--overlay-bg-weak, #ffffff99)",
    "bg-nav": "var(--overlay-bg-nav, #103b5cf5)",
  },
  ccl: {
    excellent: "var(--ccl-excellent, #196e03ff)",
    high: "var(--ccl-high, #32a113ff)",
    medium: "var(--ccl-medium, #f5b400ff)",
    low: "var(--ccl-low, #e07000ff)",
    poor: "var(--ccl-poor, #d43737ff)",
    unknown: "var(--ccl-unknown, #737373ff)",
  },
  severity: {
    critical: "var(--severity-critical, #8f1416ff)",
    high: "var(--severity-high, #d43737ff)",
    medium: "var(--severity-medium, #e07000ff)",
    low: "var(--severity-low, #f5b400ff)",
    "low-content": "var(--severity-low-content, #805700ff)",
    informational: "var(--severity-informational, #0294c9ff)",
  },
  risk: {
    poor: "var(--risk-poor, #d43737ff)",
    medium: "var(--risk-medium, #f5b400ff)",
    "medium-content": "var(--risk-medium-content, #805700ff)",
    good: "var(--risk-good, #32a113ff)",
  },
  chart: {
    "1st": "var(--chart-1st, #0294c9ff)",
    "2nd": "var(--chart-2nd, #3ededbff)",
    "3rd": "var(--chart-3rd, #67c746ff)",
    "4th": "var(--chart-4th, #ffc51aff)",
    "5th": "var(--chart-5th, #5a23adff)",
    "6th": "var(--chart-6th, #f896a1ff)",
    "7th": "var(--chart-7th, #805700ff)",
    "8th": "var(--chart-8th, #137f85ff)",
    "9th": "var(--chart-9th, #ff8200ff)",
    "10th": "var(--chart-10th, #d558d3ff)",
    other: "var(--chart-other, #737373ff)",
  },
};

const Preset = {
  theme: {
    fontFamily: {
      sans: ["Lato", ...defaultTheme.fontFamily.sans],
      serif: ["Lora", ...defaultTheme.fontFamily.serif],
      mono: ["Roboto Mono", ...defaultTheme.fontFamily.mono],
    },
    extend: {
      colors,
      maxWidth: {
        prose: "80ch",
      },
      width: {
        sm: "384px",
        md: "448px",
        xl: "576px",
        "3xl": "768px",
        "5xl": "1024px",
      },
      zIndex: {
        overlay: "100",
        modal: "200",
        dropdown: "300",
        popover: "400",
        tooltip: "500",
      },
    },
  },
};
export default Preset;
